// The collection is like a Mongo database []...

// The 'User' collection...
App.Collections.User = Backbone.Collection.extend({

	// This collection consists of these models...
	model: App.Models.User,

	// DB access: POST, PUT, DELETE...
	url: 'http://0.0.0.0:3000/collections/users'

});